# Uncomment the next line to define a global platform for your project
platform :ios, '12.1'
inhibit_all_warnings!

target 'WeatherSwift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WeatherSwift
  pod 'SwiftLint'
  pod 'SwiftMessages'
  pod 'ReachabilitySwift', '~> 4.3.0'
  pod 'SwiftGen', '~> 6.0.2'


  target 'WeatherSwiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WeatherSwiftUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'WeatherCore' do
  use_frameworks!
  
  # Pods for WeatherCore
  pod 'ReachabilitySwift', '~> 4.3.0'
  pod 'SwiftMessages'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      # This works around a unit test issue introduced in Xcode 10.
      # We only apply it to the Debug configuration to avoid bloating the app size
      if config.name == "Debug" && defined?(target.product_type) && target.product_type == "com.apple.product-type.framework"
        config.build_settings['ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES'] = "YES"
      end
    end
  end
end
