# Uncomment the next line to define a global platform for your project
platform :ios, '12.1'
inhibit_all_warnings!

target 'WeatherSwift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WeatherSwift
  pod 'SwiftLint'
  pod 'SwiftMessages'
  pod 'ReachabilitySwift', '~> 4.3.0'
  pod 'SwiftGen', '~> 6.0.2'


  target 'WeatherSwiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WeatherSwiftUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'WeatherCore' do
  use_frameworks!
  
  # Pods for WeatherCore
  pod 'ReachabilitySwift', '~> 4.3.0'

end
